source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem "devise", "~> 1.5.0"
gem "devise_ldap_authenticatable", :path => "../../"

group :test do
  gem "test-unit"
  gem "mocha"
  gem "shoulda"
  gem 'factory_girl_rails'
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
  gem "launchy"
  gem "ladle"
end

group :darwin do
  gem "autotest-growl" 
end

